/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as EpaperRouteImport } from './routes/epaper'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionSlugRouteImport } from './routes/section.$slug'
import { Route as EmbassyIdRouteImport } from './routes/embassy.$id'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AmbassadorIdRouteImport } from './routes/ambassador.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminWarMonitorRouteImport } from './routes/_authenticated/admin.war-monitor'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin.videos'
import { Route as AuthenticatedAdminTickerRouteImport } from './routes/_authenticated/admin.ticker'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminEmbassiesRouteImport } from './routes/_authenticated/admin.embassies'
import { Route as AuthenticatedAdminCommentsRouteImport } from './routes/_authenticated/admin.comments'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAmbassadorsRouteImport } from './routes/_authenticated/admin.ambassadors'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin.access'
import { Route as AuthenticatedAdminArticlesIndexRouteImport } from './routes/_authenticated/admin.articles.index'
import { Route as AuthenticatedAdminArticlesIdRouteImport } from './routes/_authenticated/admin.articles.$id'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const EpaperRoute = EpaperRouteImport.update({
  id: '/epaper',
  path: '/epaper',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSlugRoute = SectionSlugRouteImport.update({
  id: '/section/$slug',
  path: '/section/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbassyIdRoute = EmbassyIdRouteImport.update({
  id: '/embassy/$id',
  path: '/embassy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorIdRoute = AmbassadorIdRouteImport.update({
  id: '/ambassador/$id',
  path: '/ambassador/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWarMonitorRoute =
  AuthenticatedAdminWarMonitorRouteImport.update({
    id: '/war-monitor',
    path: '/war-monitor',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTickerRoute =
  AuthenticatedAdminTickerRouteImport.update({
    id: '/ticker',
    path: '/ticker',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEmbassiesRoute =
  AuthenticatedAdminEmbassiesRouteImport.update({
    id: '/embassies',
    path: '/embassies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommentsRoute =
  AuthenticatedAdminCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAmbassadorsRoute =
  AuthenticatedAdminAmbassadorsRouteImport.update({
    id: '/ambassadors',
    path: '/ambassadors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesIndexRoute =
  AuthenticatedAdminArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesIdRoute =
  AuthenticatedAdminArticlesIdRouteImport.update({
    id: '/articles/$id',
    path: '/articles/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/epaper': typeof EpaperRoute
  '/latest': typeof LatestRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/popular': typeof PopularRoute
  '/programs': typeof ProgramsRoute
  '/video': typeof VideoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ambassador/$id': typeof AmbassadorIdRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/embassy/$id': typeof EmbassyIdRoute
  '/section/$slug': typeof SectionSlugRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/ambassadors': typeof AuthenticatedAdminAmbassadorsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/embassies': typeof AuthenticatedAdminEmbassiesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin/war-monitor': typeof AuthenticatedAdminWarMonitorRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/epaper': typeof EpaperRoute
  '/latest': typeof LatestRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/popular': typeof PopularRoute
  '/programs': typeof ProgramsRoute
  '/video': typeof VideoRoute
  '/ambassador/$id': typeof AmbassadorIdRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/embassy/$id': typeof EmbassyIdRoute
  '/section/$slug': typeof SectionSlugRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/ambassadors': typeof AuthenticatedAdminAmbassadorsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/embassies': typeof AuthenticatedAdminEmbassiesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin/war-monitor': typeof AuthenticatedAdminWarMonitorRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/epaper': typeof EpaperRoute
  '/latest': typeof LatestRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/popular': typeof PopularRoute
  '/programs': typeof ProgramsRoute
  '/video': typeof VideoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ambassador/$id': typeof AmbassadorIdRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/embassy/$id': typeof EmbassyIdRoute
  '/section/$slug': typeof SectionSlugRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/ambassadors': typeof AuthenticatedAdminAmbassadorsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/_authenticated/admin/embassies': typeof AuthenticatedAdminEmbassiesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/_authenticated/admin/war-monitor': typeof AuthenticatedAdminWarMonitorRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/_authenticated/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/epaper'
    | '/latest'
    | '/newsletter'
    | '/podcast'
    | '/popular'
    | '/programs'
    | '/video'
    | '/admin'
    | '/ambassador/$id'
    | '/article/$slug'
    | '/embassy/$id'
    | '/section/$slug'
    | '/admin/access'
    | '/admin/ambassadors'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/embassies'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/ticker'
    | '/admin/videos'
    | '/admin/war-monitor'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/epaper'
    | '/latest'
    | '/newsletter'
    | '/podcast'
    | '/popular'
    | '/programs'
    | '/video'
    | '/ambassador/$id'
    | '/article/$slug'
    | '/embassy/$id'
    | '/section/$slug'
    | '/admin/access'
    | '/admin/ambassadors'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/embassies'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/ticker'
    | '/admin/videos'
    | '/admin/war-monitor'
    | '/admin'
    | '/admin/articles/$id'
    | '/admin/articles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/epaper'
    | '/latest'
    | '/newsletter'
    | '/podcast'
    | '/popular'
    | '/programs'
    | '/video'
    | '/_authenticated/admin'
    | '/ambassador/$id'
    | '/article/$slug'
    | '/embassy/$id'
    | '/section/$slug'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/ambassadors'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/comments'
    | '/_authenticated/admin/embassies'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/ticker'
    | '/_authenticated/admin/videos'
    | '/_authenticated/admin/war-monitor'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/articles/$id'
    | '/_authenticated/admin/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  EpaperRoute: typeof EpaperRoute
  LatestRoute: typeof LatestRoute
  NewsletterRoute: typeof NewsletterRoute
  PodcastRoute: typeof PodcastRoute
  PopularRoute: typeof PopularRoute
  ProgramsRoute: typeof ProgramsRoute
  VideoRoute: typeof VideoRoute
  AmbassadorIdRoute: typeof AmbassadorIdRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  EmbassyIdRoute: typeof EmbassyIdRoute
  SectionSlugRoute: typeof SectionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epaper': {
      id: '/epaper'
      path: '/epaper'
      fullPath: '/epaper'
      preLoaderRoute: typeof EpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$slug': {
      id: '/section/$slug'
      path: '/section/$slug'
      fullPath: '/section/$slug'
      preLoaderRoute: typeof SectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embassy/$id': {
      id: '/embassy/$id'
      path: '/embassy/$id'
      fullPath: '/embassy/$id'
      preLoaderRoute: typeof EmbassyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador/$id': {
      id: '/ambassador/$id'
      path: '/ambassador/$id'
      fullPath: '/ambassador/$id'
      preLoaderRoute: typeof AmbassadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/war-monitor': {
      id: '/_authenticated/admin/war-monitor'
      path: '/war-monitor'
      fullPath: '/admin/war-monitor'
      preLoaderRoute: typeof AuthenticatedAdminWarMonitorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ticker': {
      id: '/_authenticated/admin/ticker'
      path: '/ticker'
      fullPath: '/admin/ticker'
      preLoaderRoute: typeof AuthenticatedAdminTickerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/embassies': {
      id: '/_authenticated/admin/embassies'
      path: '/embassies'
      fullPath: '/admin/embassies'
      preLoaderRoute: typeof AuthenticatedAdminEmbassiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comments': {
      id: '/_authenticated/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AuthenticatedAdminCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ambassadors': {
      id: '/_authenticated/admin/ambassadors'
      path: '/ambassadors'
      fullPath: '/admin/ambassadors'
      preLoaderRoute: typeof AuthenticatedAdminAmbassadorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles/': {
      id: '/_authenticated/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles/$id': {
      id: '/_authenticated/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminAmbassadorsRoute: typeof AuthenticatedAdminAmbassadorsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCommentsRoute: typeof AuthenticatedAdminCommentsRoute
  AuthenticatedAdminEmbassiesRoute: typeof AuthenticatedAdminEmbassiesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTickerRoute: typeof AuthenticatedAdminTickerRoute
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAdminWarMonitorRoute: typeof AuthenticatedAdminWarMonitorRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminArticlesIdRoute: typeof AuthenticatedAdminArticlesIdRoute
  AuthenticatedAdminArticlesIndexRoute: typeof AuthenticatedAdminArticlesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminAmbassadorsRoute: AuthenticatedAdminAmbassadorsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCommentsRoute: AuthenticatedAdminCommentsRoute,
  AuthenticatedAdminEmbassiesRoute: AuthenticatedAdminEmbassiesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTickerRoute: AuthenticatedAdminTickerRoute,
  AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
  AuthenticatedAdminWarMonitorRoute: AuthenticatedAdminWarMonitorRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminArticlesIdRoute: AuthenticatedAdminArticlesIdRoute,
  AuthenticatedAdminArticlesIndexRoute: AuthenticatedAdminArticlesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  EpaperRoute: EpaperRoute,
  LatestRoute: LatestRoute,
  NewsletterRoute: NewsletterRoute,
  PodcastRoute: PodcastRoute,
  PopularRoute: PopularRoute,
  ProgramsRoute: ProgramsRoute,
  VideoRoute: VideoRoute,
  AmbassadorIdRoute: AmbassadorIdRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  EmbassyIdRoute: EmbassyIdRoute,
  SectionSlugRoute: SectionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
