/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as EpaperRouteImport } from './routes/epaper'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionSlugRouteImport } from './routes/section.$slug'
import { Route as EmbassyIdRouteImport } from './routes/embassy.$id'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AmbassadorIdRouteImport } from './routes/ambassador.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminWarMonitorRouteImport } from './routes/_authenticated/admin.war-monitor'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin.videos'
import { Route as AuthenticatedAdminTickerRouteImport } from './routes/_authenticated/admin.ticker'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminEmbassiesRouteImport } from './routes/_authenticated/admin.embassies'
import { Route as AuthenticatedAdminCommentsRouteImport } from './routes/_authenticated/admin.comments'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAmbassadorsRouteImport } from './routes/_authenticated/admin.ambassadors'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin.access'
import { Route as AuthenticatedAdminCategoriesIndexRouteImport } from './routes/_authenticated/admin.categories.index'
import { Route as AuthenticatedAdminArticlesIndexRouteImport } from './routes/_authenticated/admin.articles.index'
import { Route as AuthenticatedAdminCategoriesSettingsRouteImport } from './routes/_authenticated/admin.categories.settings'
import { Route as AuthenticatedAdminCategoriesImportExportRouteImport } from './routes/_authenticated/admin.categories.import-export'
import { Route as AuthenticatedAdminCategoriesCreateRouteImport } from './routes/_authenticated/admin.categories.create'
import { Route as AuthenticatedAdminCategoriesAllRouteImport } from './routes/_authenticated/admin.categories.all'
import { Route as AuthenticatedAdminCategoriesActivityRouteImport } from './routes/_authenticated/admin.categories.activity'
import { Route as AuthenticatedAdminCategoriesIdRouteImport } from './routes/_authenticated/admin.categories.$id'
import { Route as AuthenticatedAdminArticlesWorkflowRouteImport } from './routes/_authenticated/admin.articles.workflow'
import { Route as AuthenticatedAdminArticlesTrashRouteImport } from './routes/_authenticated/admin.articles.trash'
import { Route as AuthenticatedAdminArticlesSettingsRouteImport } from './routes/_authenticated/admin.articles.settings'
import { Route as AuthenticatedAdminArticlesScheduledRouteImport } from './routes/_authenticated/admin.articles.scheduled'
import { Route as AuthenticatedAdminArticlesRevisionsRouteImport } from './routes/_authenticated/admin.articles.revisions'
import { Route as AuthenticatedAdminArticlesReviewRouteImport } from './routes/_authenticated/admin.articles.review'
import { Route as AuthenticatedAdminArticlesRelatedRouteImport } from './routes/_authenticated/admin.articles.related'
import { Route as AuthenticatedAdminArticlesPublishedRouteImport } from './routes/_authenticated/admin.articles.published'
import { Route as AuthenticatedAdminArticlesPreviewRouteImport } from './routes/_authenticated/admin.articles.preview'
import { Route as AuthenticatedAdminArticlesInternalLinkingRouteImport } from './routes/_authenticated/admin.articles.internal-linking'
import { Route as AuthenticatedAdminArticlesDraftsRouteImport } from './routes/_authenticated/admin.articles.drafts'
import { Route as AuthenticatedAdminArticlesCreateRouteImport } from './routes/_authenticated/admin.articles.create'
import { Route as AuthenticatedAdminArticlesContentScoreRouteImport } from './routes/_authenticated/admin.articles.content-score'
import { Route as AuthenticatedAdminArticlesArchivedRouteImport } from './routes/_authenticated/admin.articles.archived'
import { Route as AuthenticatedAdminArticlesApprovedRouteImport } from './routes/_authenticated/admin.articles.approved'
import { Route as AuthenticatedAdminArticlesAllRouteImport } from './routes/_authenticated/admin.articles.all'
import { Route as AuthenticatedAdminArticlesAiWritingRouteImport } from './routes/_authenticated/admin.articles.ai-writing'
import { Route as AuthenticatedAdminArticlesAiSeoRouteImport } from './routes/_authenticated/admin.articles.ai-seo'
import { Route as AuthenticatedAdminArticlesIdRouteImport } from './routes/_authenticated/admin.articles.$id'
import { Route as AuthenticatedAdminArticlesRevisionsIndexRouteImport } from './routes/_authenticated/admin.articles.revisions.index'
import { Route as AuthenticatedAdminArticlesPreviewIndexRouteImport } from './routes/_authenticated/admin.articles.preview.index'
import { Route as AuthenticatedAdminCategoriesIdSettingsRouteImport } from './routes/_authenticated/admin.categories.$id.settings'
import { Route as AuthenticatedAdminCategoriesIdEditRouteImport } from './routes/_authenticated/admin.categories.$id.edit'
import { Route as AuthenticatedAdminCategoriesIdArticlesRouteImport } from './routes/_authenticated/admin.categories.$id.articles'
import { Route as AuthenticatedAdminCategoriesIdAnalyticsRouteImport } from './routes/_authenticated/admin.categories.$id.analytics'
import { Route as AuthenticatedAdminArticlesRevisionsArticleIdRouteImport } from './routes/_authenticated/admin.articles.revisions.$articleId'
import { Route as AuthenticatedAdminArticlesPreviewArticleIdRouteImport } from './routes/_authenticated/admin.articles.preview.$articleId'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const EpaperRoute = EpaperRouteImport.update({
  id: '/epaper',
  path: '/epaper',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSlugRoute = SectionSlugRouteImport.update({
  id: '/section/$slug',
  path: '/section/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbassyIdRoute = EmbassyIdRouteImport.update({
  id: '/embassy/$id',
  path: '/embassy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorIdRoute = AmbassadorIdRouteImport.update({
  id: '/ambassador/$id',
  path: '/ambassador/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWarMonitorRoute =
  AuthenticatedAdminWarMonitorRouteImport.update({
    id: '/war-monitor',
    path: '/war-monitor',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTickerRoute =
  AuthenticatedAdminTickerRouteImport.update({
    id: '/ticker',
    path: '/ticker',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEmbassiesRoute =
  AuthenticatedAdminEmbassiesRouteImport.update({
    id: '/embassies',
    path: '/embassies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommentsRoute =
  AuthenticatedAdminCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAmbassadorsRoute =
  AuthenticatedAdminAmbassadorsRouteImport.update({
    id: '/ambassadors',
    path: '/ambassadors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesIndexRoute =
  AuthenticatedAdminCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminArticlesIndexRoute =
  AuthenticatedAdminArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminCategoriesSettingsRoute =
  AuthenticatedAdminCategoriesSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminCategoriesImportExportRoute =
  AuthenticatedAdminCategoriesImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminCategoriesCreateRoute =
  AuthenticatedAdminCategoriesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminCategoriesAllRoute =
  AuthenticatedAdminCategoriesAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminCategoriesActivityRoute =
  AuthenticatedAdminCategoriesActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminCategoriesIdRoute =
  AuthenticatedAdminCategoriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminArticlesWorkflowRoute =
  AuthenticatedAdminArticlesWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesTrashRoute =
  AuthenticatedAdminArticlesTrashRouteImport.update({
    id: '/trash',
    path: '/trash',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesSettingsRoute =
  AuthenticatedAdminArticlesSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesScheduledRoute =
  AuthenticatedAdminArticlesScheduledRouteImport.update({
    id: '/scheduled',
    path: '/scheduled',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesRevisionsRoute =
  AuthenticatedAdminArticlesRevisionsRouteImport.update({
    id: '/revisions',
    path: '/revisions',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesReviewRoute =
  AuthenticatedAdminArticlesReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesRelatedRoute =
  AuthenticatedAdminArticlesRelatedRouteImport.update({
    id: '/related',
    path: '/related',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesPublishedRoute =
  AuthenticatedAdminArticlesPublishedRouteImport.update({
    id: '/published',
    path: '/published',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesPreviewRoute =
  AuthenticatedAdminArticlesPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesInternalLinkingRoute =
  AuthenticatedAdminArticlesInternalLinkingRouteImport.update({
    id: '/internal-linking',
    path: '/internal-linking',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesDraftsRoute =
  AuthenticatedAdminArticlesDraftsRouteImport.update({
    id: '/drafts',
    path: '/drafts',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesCreateRoute =
  AuthenticatedAdminArticlesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesContentScoreRoute =
  AuthenticatedAdminArticlesContentScoreRouteImport.update({
    id: '/content-score',
    path: '/content-score',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesArchivedRoute =
  AuthenticatedAdminArticlesArchivedRouteImport.update({
    id: '/archived',
    path: '/archived',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesApprovedRoute =
  AuthenticatedAdminArticlesApprovedRouteImport.update({
    id: '/approved',
    path: '/approved',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesAllRoute =
  AuthenticatedAdminArticlesAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesAiWritingRoute =
  AuthenticatedAdminArticlesAiWritingRouteImport.update({
    id: '/ai-writing',
    path: '/ai-writing',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesAiSeoRoute =
  AuthenticatedAdminArticlesAiSeoRouteImport.update({
    id: '/ai-seo',
    path: '/ai-seo',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesIdRoute =
  AuthenticatedAdminArticlesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesRevisionsIndexRoute =
  AuthenticatedAdminArticlesRevisionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminArticlesRevisionsRoute,
  } as any)
const AuthenticatedAdminArticlesPreviewIndexRoute =
  AuthenticatedAdminArticlesPreviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminArticlesPreviewRoute,
  } as any)
const AuthenticatedAdminCategoriesIdSettingsRoute =
  AuthenticatedAdminCategoriesIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminCategoriesIdRoute,
  } as any)
const AuthenticatedAdminCategoriesIdEditRoute =
  AuthenticatedAdminCategoriesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAdminCategoriesIdRoute,
  } as any)
const AuthenticatedAdminCategoriesIdArticlesRoute =
  AuthenticatedAdminCategoriesIdArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminCategoriesIdRoute,
  } as any)
const AuthenticatedAdminCategoriesIdAnalyticsRoute =
  AuthenticatedAdminCategoriesIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminCategoriesIdRoute,
  } as any)
const AuthenticatedAdminArticlesRevisionsArticleIdRoute =
  AuthenticatedAdminArticlesRevisionsArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => AuthenticatedAdminArticlesRevisionsRoute,
  } as any)
const AuthenticatedAdminArticlesPreviewArticleIdRoute =
  AuthenticatedAdminArticlesPreviewArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => AuthenticatedAdminArticlesPreviewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/epaper': typeof EpaperRoute
  '/latest': typeof LatestRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/popular': typeof PopularRoute
  '/programs': typeof ProgramsRoute
  '/video': typeof VideoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ambassador/$id': typeof AmbassadorIdRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/embassy/$id': typeof EmbassyIdRoute
  '/section/$slug': typeof SectionSlugRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/ambassadors': typeof AuthenticatedAdminAmbassadorsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRouteWithChildren
  '/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/embassies': typeof AuthenticatedAdminEmbassiesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin/war-monitor': typeof AuthenticatedAdminWarMonitorRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/admin/articles/ai-seo': typeof AuthenticatedAdminArticlesAiSeoRoute
  '/admin/articles/ai-writing': typeof AuthenticatedAdminArticlesAiWritingRoute
  '/admin/articles/all': typeof AuthenticatedAdminArticlesAllRoute
  '/admin/articles/approved': typeof AuthenticatedAdminArticlesApprovedRoute
  '/admin/articles/archived': typeof AuthenticatedAdminArticlesArchivedRoute
  '/admin/articles/content-score': typeof AuthenticatedAdminArticlesContentScoreRoute
  '/admin/articles/create': typeof AuthenticatedAdminArticlesCreateRoute
  '/admin/articles/drafts': typeof AuthenticatedAdminArticlesDraftsRoute
  '/admin/articles/internal-linking': typeof AuthenticatedAdminArticlesInternalLinkingRoute
  '/admin/articles/preview': typeof AuthenticatedAdminArticlesPreviewRouteWithChildren
  '/admin/articles/published': typeof AuthenticatedAdminArticlesPublishedRoute
  '/admin/articles/related': typeof AuthenticatedAdminArticlesRelatedRoute
  '/admin/articles/review': typeof AuthenticatedAdminArticlesReviewRoute
  '/admin/articles/revisions': typeof AuthenticatedAdminArticlesRevisionsRouteWithChildren
  '/admin/articles/scheduled': typeof AuthenticatedAdminArticlesScheduledRoute
  '/admin/articles/settings': typeof AuthenticatedAdminArticlesSettingsRoute
  '/admin/articles/trash': typeof AuthenticatedAdminArticlesTrashRoute
  '/admin/articles/workflow': typeof AuthenticatedAdminArticlesWorkflowRoute
  '/admin/categories/$id': typeof AuthenticatedAdminCategoriesIdRouteWithChildren
  '/admin/categories/activity': typeof AuthenticatedAdminCategoriesActivityRoute
  '/admin/categories/all': typeof AuthenticatedAdminCategoriesAllRoute
  '/admin/categories/create': typeof AuthenticatedAdminCategoriesCreateRoute
  '/admin/categories/import-export': typeof AuthenticatedAdminCategoriesImportExportRoute
  '/admin/categories/settings': typeof AuthenticatedAdminCategoriesSettingsRoute
  '/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
  '/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/articles/preview/$articleId': typeof AuthenticatedAdminArticlesPreviewArticleIdRoute
  '/admin/articles/revisions/$articleId': typeof AuthenticatedAdminArticlesRevisionsArticleIdRoute
  '/admin/categories/$id/analytics': typeof AuthenticatedAdminCategoriesIdAnalyticsRoute
  '/admin/categories/$id/articles': typeof AuthenticatedAdminCategoriesIdArticlesRoute
  '/admin/categories/$id/edit': typeof AuthenticatedAdminCategoriesIdEditRoute
  '/admin/categories/$id/settings': typeof AuthenticatedAdminCategoriesIdSettingsRoute
  '/admin/articles/preview/': typeof AuthenticatedAdminArticlesPreviewIndexRoute
  '/admin/articles/revisions/': typeof AuthenticatedAdminArticlesRevisionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/epaper': typeof EpaperRoute
  '/latest': typeof LatestRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/popular': typeof PopularRoute
  '/programs': typeof ProgramsRoute
  '/video': typeof VideoRoute
  '/ambassador/$id': typeof AmbassadorIdRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/embassy/$id': typeof EmbassyIdRoute
  '/section/$slug': typeof SectionSlugRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/ambassadors': typeof AuthenticatedAdminAmbassadorsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/embassies': typeof AuthenticatedAdminEmbassiesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin/war-monitor': typeof AuthenticatedAdminWarMonitorRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/admin/articles/ai-seo': typeof AuthenticatedAdminArticlesAiSeoRoute
  '/admin/articles/ai-writing': typeof AuthenticatedAdminArticlesAiWritingRoute
  '/admin/articles/all': typeof AuthenticatedAdminArticlesAllRoute
  '/admin/articles/approved': typeof AuthenticatedAdminArticlesApprovedRoute
  '/admin/articles/archived': typeof AuthenticatedAdminArticlesArchivedRoute
  '/admin/articles/content-score': typeof AuthenticatedAdminArticlesContentScoreRoute
  '/admin/articles/create': typeof AuthenticatedAdminArticlesCreateRoute
  '/admin/articles/drafts': typeof AuthenticatedAdminArticlesDraftsRoute
  '/admin/articles/internal-linking': typeof AuthenticatedAdminArticlesInternalLinkingRoute
  '/admin/articles/published': typeof AuthenticatedAdminArticlesPublishedRoute
  '/admin/articles/related': typeof AuthenticatedAdminArticlesRelatedRoute
  '/admin/articles/review': typeof AuthenticatedAdminArticlesReviewRoute
  '/admin/articles/scheduled': typeof AuthenticatedAdminArticlesScheduledRoute
  '/admin/articles/settings': typeof AuthenticatedAdminArticlesSettingsRoute
  '/admin/articles/trash': typeof AuthenticatedAdminArticlesTrashRoute
  '/admin/articles/workflow': typeof AuthenticatedAdminArticlesWorkflowRoute
  '/admin/categories/$id': typeof AuthenticatedAdminCategoriesIdRouteWithChildren
  '/admin/categories/activity': typeof AuthenticatedAdminCategoriesActivityRoute
  '/admin/categories/all': typeof AuthenticatedAdminCategoriesAllRoute
  '/admin/categories/create': typeof AuthenticatedAdminCategoriesCreateRoute
  '/admin/categories/import-export': typeof AuthenticatedAdminCategoriesImportExportRoute
  '/admin/categories/settings': typeof AuthenticatedAdminCategoriesSettingsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/articles/preview/$articleId': typeof AuthenticatedAdminArticlesPreviewArticleIdRoute
  '/admin/articles/revisions/$articleId': typeof AuthenticatedAdminArticlesRevisionsArticleIdRoute
  '/admin/categories/$id/analytics': typeof AuthenticatedAdminCategoriesIdAnalyticsRoute
  '/admin/categories/$id/articles': typeof AuthenticatedAdminCategoriesIdArticlesRoute
  '/admin/categories/$id/edit': typeof AuthenticatedAdminCategoriesIdEditRoute
  '/admin/categories/$id/settings': typeof AuthenticatedAdminCategoriesIdSettingsRoute
  '/admin/articles/preview': typeof AuthenticatedAdminArticlesPreviewIndexRoute
  '/admin/articles/revisions': typeof AuthenticatedAdminArticlesRevisionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/epaper': typeof EpaperRoute
  '/latest': typeof LatestRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/popular': typeof PopularRoute
  '/programs': typeof ProgramsRoute
  '/video': typeof VideoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ambassador/$id': typeof AmbassadorIdRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/embassy/$id': typeof EmbassyIdRoute
  '/section/$slug': typeof SectionSlugRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/ambassadors': typeof AuthenticatedAdminAmbassadorsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRouteWithChildren
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/_authenticated/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/_authenticated/admin/embassies': typeof AuthenticatedAdminEmbassiesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/ticker': typeof AuthenticatedAdminTickerRoute
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/_authenticated/admin/war-monitor': typeof AuthenticatedAdminWarMonitorRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/_authenticated/admin/articles/ai-seo': typeof AuthenticatedAdminArticlesAiSeoRoute
  '/_authenticated/admin/articles/ai-writing': typeof AuthenticatedAdminArticlesAiWritingRoute
  '/_authenticated/admin/articles/all': typeof AuthenticatedAdminArticlesAllRoute
  '/_authenticated/admin/articles/approved': typeof AuthenticatedAdminArticlesApprovedRoute
  '/_authenticated/admin/articles/archived': typeof AuthenticatedAdminArticlesArchivedRoute
  '/_authenticated/admin/articles/content-score': typeof AuthenticatedAdminArticlesContentScoreRoute
  '/_authenticated/admin/articles/create': typeof AuthenticatedAdminArticlesCreateRoute
  '/_authenticated/admin/articles/drafts': typeof AuthenticatedAdminArticlesDraftsRoute
  '/_authenticated/admin/articles/internal-linking': typeof AuthenticatedAdminArticlesInternalLinkingRoute
  '/_authenticated/admin/articles/preview': typeof AuthenticatedAdminArticlesPreviewRouteWithChildren
  '/_authenticated/admin/articles/published': typeof AuthenticatedAdminArticlesPublishedRoute
  '/_authenticated/admin/articles/related': typeof AuthenticatedAdminArticlesRelatedRoute
  '/_authenticated/admin/articles/review': typeof AuthenticatedAdminArticlesReviewRoute
  '/_authenticated/admin/articles/revisions': typeof AuthenticatedAdminArticlesRevisionsRouteWithChildren
  '/_authenticated/admin/articles/scheduled': typeof AuthenticatedAdminArticlesScheduledRoute
  '/_authenticated/admin/articles/settings': typeof AuthenticatedAdminArticlesSettingsRoute
  '/_authenticated/admin/articles/trash': typeof AuthenticatedAdminArticlesTrashRoute
  '/_authenticated/admin/articles/workflow': typeof AuthenticatedAdminArticlesWorkflowRoute
  '/_authenticated/admin/categories/$id': typeof AuthenticatedAdminCategoriesIdRouteWithChildren
  '/_authenticated/admin/categories/activity': typeof AuthenticatedAdminCategoriesActivityRoute
  '/_authenticated/admin/categories/all': typeof AuthenticatedAdminCategoriesAllRoute
  '/_authenticated/admin/categories/create': typeof AuthenticatedAdminCategoriesCreateRoute
  '/_authenticated/admin/categories/import-export': typeof AuthenticatedAdminCategoriesImportExportRoute
  '/_authenticated/admin/categories/settings': typeof AuthenticatedAdminCategoriesSettingsRoute
  '/_authenticated/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
  '/_authenticated/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/_authenticated/admin/articles/preview/$articleId': typeof AuthenticatedAdminArticlesPreviewArticleIdRoute
  '/_authenticated/admin/articles/revisions/$articleId': typeof AuthenticatedAdminArticlesRevisionsArticleIdRoute
  '/_authenticated/admin/categories/$id/analytics': typeof AuthenticatedAdminCategoriesIdAnalyticsRoute
  '/_authenticated/admin/categories/$id/articles': typeof AuthenticatedAdminCategoriesIdArticlesRoute
  '/_authenticated/admin/categories/$id/edit': typeof AuthenticatedAdminCategoriesIdEditRoute
  '/_authenticated/admin/categories/$id/settings': typeof AuthenticatedAdminCategoriesIdSettingsRoute
  '/_authenticated/admin/articles/preview/': typeof AuthenticatedAdminArticlesPreviewIndexRoute
  '/_authenticated/admin/articles/revisions/': typeof AuthenticatedAdminArticlesRevisionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/epaper'
    | '/latest'
    | '/newsletter'
    | '/podcast'
    | '/popular'
    | '/programs'
    | '/video'
    | '/admin'
    | '/ambassador/$id'
    | '/article/$slug'
    | '/embassy/$id'
    | '/section/$slug'
    | '/admin/access'
    | '/admin/ambassadors'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/embassies'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/ticker'
    | '/admin/videos'
    | '/admin/war-monitor'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/ai-seo'
    | '/admin/articles/ai-writing'
    | '/admin/articles/all'
    | '/admin/articles/approved'
    | '/admin/articles/archived'
    | '/admin/articles/content-score'
    | '/admin/articles/create'
    | '/admin/articles/drafts'
    | '/admin/articles/internal-linking'
    | '/admin/articles/preview'
    | '/admin/articles/published'
    | '/admin/articles/related'
    | '/admin/articles/review'
    | '/admin/articles/revisions'
    | '/admin/articles/scheduled'
    | '/admin/articles/settings'
    | '/admin/articles/trash'
    | '/admin/articles/workflow'
    | '/admin/categories/$id'
    | '/admin/categories/activity'
    | '/admin/categories/all'
    | '/admin/categories/create'
    | '/admin/categories/import-export'
    | '/admin/categories/settings'
    | '/admin/articles/'
    | '/admin/categories/'
    | '/admin/articles/preview/$articleId'
    | '/admin/articles/revisions/$articleId'
    | '/admin/categories/$id/analytics'
    | '/admin/categories/$id/articles'
    | '/admin/categories/$id/edit'
    | '/admin/categories/$id/settings'
    | '/admin/articles/preview/'
    | '/admin/articles/revisions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/epaper'
    | '/latest'
    | '/newsletter'
    | '/podcast'
    | '/popular'
    | '/programs'
    | '/video'
    | '/ambassador/$id'
    | '/article/$slug'
    | '/embassy/$id'
    | '/section/$slug'
    | '/admin/access'
    | '/admin/ambassadors'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/embassies'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/ticker'
    | '/admin/videos'
    | '/admin/war-monitor'
    | '/admin'
    | '/admin/articles/$id'
    | '/admin/articles/ai-seo'
    | '/admin/articles/ai-writing'
    | '/admin/articles/all'
    | '/admin/articles/approved'
    | '/admin/articles/archived'
    | '/admin/articles/content-score'
    | '/admin/articles/create'
    | '/admin/articles/drafts'
    | '/admin/articles/internal-linking'
    | '/admin/articles/published'
    | '/admin/articles/related'
    | '/admin/articles/review'
    | '/admin/articles/scheduled'
    | '/admin/articles/settings'
    | '/admin/articles/trash'
    | '/admin/articles/workflow'
    | '/admin/categories/$id'
    | '/admin/categories/activity'
    | '/admin/categories/all'
    | '/admin/categories/create'
    | '/admin/categories/import-export'
    | '/admin/categories/settings'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/articles/preview/$articleId'
    | '/admin/articles/revisions/$articleId'
    | '/admin/categories/$id/analytics'
    | '/admin/categories/$id/articles'
    | '/admin/categories/$id/edit'
    | '/admin/categories/$id/settings'
    | '/admin/articles/preview'
    | '/admin/articles/revisions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/epaper'
    | '/latest'
    | '/newsletter'
    | '/podcast'
    | '/popular'
    | '/programs'
    | '/video'
    | '/_authenticated/admin'
    | '/ambassador/$id'
    | '/article/$slug'
    | '/embassy/$id'
    | '/section/$slug'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/ambassadors'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/comments'
    | '/_authenticated/admin/embassies'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/ticker'
    | '/_authenticated/admin/videos'
    | '/_authenticated/admin/war-monitor'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/articles/$id'
    | '/_authenticated/admin/articles/ai-seo'
    | '/_authenticated/admin/articles/ai-writing'
    | '/_authenticated/admin/articles/all'
    | '/_authenticated/admin/articles/approved'
    | '/_authenticated/admin/articles/archived'
    | '/_authenticated/admin/articles/content-score'
    | '/_authenticated/admin/articles/create'
    | '/_authenticated/admin/articles/drafts'
    | '/_authenticated/admin/articles/internal-linking'
    | '/_authenticated/admin/articles/preview'
    | '/_authenticated/admin/articles/published'
    | '/_authenticated/admin/articles/related'
    | '/_authenticated/admin/articles/review'
    | '/_authenticated/admin/articles/revisions'
    | '/_authenticated/admin/articles/scheduled'
    | '/_authenticated/admin/articles/settings'
    | '/_authenticated/admin/articles/trash'
    | '/_authenticated/admin/articles/workflow'
    | '/_authenticated/admin/categories/$id'
    | '/_authenticated/admin/categories/activity'
    | '/_authenticated/admin/categories/all'
    | '/_authenticated/admin/categories/create'
    | '/_authenticated/admin/categories/import-export'
    | '/_authenticated/admin/categories/settings'
    | '/_authenticated/admin/articles/'
    | '/_authenticated/admin/categories/'
    | '/_authenticated/admin/articles/preview/$articleId'
    | '/_authenticated/admin/articles/revisions/$articleId'
    | '/_authenticated/admin/categories/$id/analytics'
    | '/_authenticated/admin/categories/$id/articles'
    | '/_authenticated/admin/categories/$id/edit'
    | '/_authenticated/admin/categories/$id/settings'
    | '/_authenticated/admin/articles/preview/'
    | '/_authenticated/admin/articles/revisions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  EpaperRoute: typeof EpaperRoute
  LatestRoute: typeof LatestRoute
  NewsletterRoute: typeof NewsletterRoute
  PodcastRoute: typeof PodcastRoute
  PopularRoute: typeof PopularRoute
  ProgramsRoute: typeof ProgramsRoute
  VideoRoute: typeof VideoRoute
  AmbassadorIdRoute: typeof AmbassadorIdRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  EmbassyIdRoute: typeof EmbassyIdRoute
  SectionSlugRoute: typeof SectionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epaper': {
      id: '/epaper'
      path: '/epaper'
      fullPath: '/epaper'
      preLoaderRoute: typeof EpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$slug': {
      id: '/section/$slug'
      path: '/section/$slug'
      fullPath: '/section/$slug'
      preLoaderRoute: typeof SectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embassy/$id': {
      id: '/embassy/$id'
      path: '/embassy/$id'
      fullPath: '/embassy/$id'
      preLoaderRoute: typeof EmbassyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador/$id': {
      id: '/ambassador/$id'
      path: '/ambassador/$id'
      fullPath: '/ambassador/$id'
      preLoaderRoute: typeof AmbassadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/war-monitor': {
      id: '/_authenticated/admin/war-monitor'
      path: '/war-monitor'
      fullPath: '/admin/war-monitor'
      preLoaderRoute: typeof AuthenticatedAdminWarMonitorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ticker': {
      id: '/_authenticated/admin/ticker'
      path: '/ticker'
      fullPath: '/admin/ticker'
      preLoaderRoute: typeof AuthenticatedAdminTickerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/embassies': {
      id: '/_authenticated/admin/embassies'
      path: '/embassies'
      fullPath: '/admin/embassies'
      preLoaderRoute: typeof AuthenticatedAdminEmbassiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comments': {
      id: '/_authenticated/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AuthenticatedAdminCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ambassadors': {
      id: '/_authenticated/admin/ambassadors'
      path: '/ambassadors'
      fullPath: '/admin/ambassadors'
      preLoaderRoute: typeof AuthenticatedAdminAmbassadorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories/': {
      id: '/_authenticated/admin/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/articles/': {
      id: '/_authenticated/admin/articles/'
      path: '/'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/categories/settings': {
      id: '/_authenticated/admin/categories/settings'
      path: '/settings'
      fullPath: '/admin/categories/settings'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/categories/import-export': {
      id: '/_authenticated/admin/categories/import-export'
      path: '/import-export'
      fullPath: '/admin/categories/import-export'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesImportExportRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/categories/create': {
      id: '/_authenticated/admin/categories/create'
      path: '/create'
      fullPath: '/admin/categories/create'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesCreateRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/categories/all': {
      id: '/_authenticated/admin/categories/all'
      path: '/all'
      fullPath: '/admin/categories/all'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesAllRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/categories/activity': {
      id: '/_authenticated/admin/categories/activity'
      path: '/activity'
      fullPath: '/admin/categories/activity'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesActivityRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/categories/$id': {
      id: '/_authenticated/admin/categories/$id'
      path: '/$id'
      fullPath: '/admin/categories/$id'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIdRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/articles/workflow': {
      id: '/_authenticated/admin/articles/workflow'
      path: '/workflow'
      fullPath: '/admin/articles/workflow'
      preLoaderRoute: typeof AuthenticatedAdminArticlesWorkflowRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/trash': {
      id: '/_authenticated/admin/articles/trash'
      path: '/trash'
      fullPath: '/admin/articles/trash'
      preLoaderRoute: typeof AuthenticatedAdminArticlesTrashRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/settings': {
      id: '/_authenticated/admin/articles/settings'
      path: '/settings'
      fullPath: '/admin/articles/settings'
      preLoaderRoute: typeof AuthenticatedAdminArticlesSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/scheduled': {
      id: '/_authenticated/admin/articles/scheduled'
      path: '/scheduled'
      fullPath: '/admin/articles/scheduled'
      preLoaderRoute: typeof AuthenticatedAdminArticlesScheduledRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/revisions': {
      id: '/_authenticated/admin/articles/revisions'
      path: '/revisions'
      fullPath: '/admin/articles/revisions'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRevisionsRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/review': {
      id: '/_authenticated/admin/articles/review'
      path: '/review'
      fullPath: '/admin/articles/review'
      preLoaderRoute: typeof AuthenticatedAdminArticlesReviewRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/related': {
      id: '/_authenticated/admin/articles/related'
      path: '/related'
      fullPath: '/admin/articles/related'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRelatedRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/published': {
      id: '/_authenticated/admin/articles/published'
      path: '/published'
      fullPath: '/admin/articles/published'
      preLoaderRoute: typeof AuthenticatedAdminArticlesPublishedRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/preview': {
      id: '/_authenticated/admin/articles/preview'
      path: '/preview'
      fullPath: '/admin/articles/preview'
      preLoaderRoute: typeof AuthenticatedAdminArticlesPreviewRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/internal-linking': {
      id: '/_authenticated/admin/articles/internal-linking'
      path: '/internal-linking'
      fullPath: '/admin/articles/internal-linking'
      preLoaderRoute: typeof AuthenticatedAdminArticlesInternalLinkingRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/drafts': {
      id: '/_authenticated/admin/articles/drafts'
      path: '/drafts'
      fullPath: '/admin/articles/drafts'
      preLoaderRoute: typeof AuthenticatedAdminArticlesDraftsRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/create': {
      id: '/_authenticated/admin/articles/create'
      path: '/create'
      fullPath: '/admin/articles/create'
      preLoaderRoute: typeof AuthenticatedAdminArticlesCreateRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/content-score': {
      id: '/_authenticated/admin/articles/content-score'
      path: '/content-score'
      fullPath: '/admin/articles/content-score'
      preLoaderRoute: typeof AuthenticatedAdminArticlesContentScoreRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/archived': {
      id: '/_authenticated/admin/articles/archived'
      path: '/archived'
      fullPath: '/admin/articles/archived'
      preLoaderRoute: typeof AuthenticatedAdminArticlesArchivedRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/approved': {
      id: '/_authenticated/admin/articles/approved'
      path: '/approved'
      fullPath: '/admin/articles/approved'
      preLoaderRoute: typeof AuthenticatedAdminArticlesApprovedRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/all': {
      id: '/_authenticated/admin/articles/all'
      path: '/all'
      fullPath: '/admin/articles/all'
      preLoaderRoute: typeof AuthenticatedAdminArticlesAllRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/ai-writing': {
      id: '/_authenticated/admin/articles/ai-writing'
      path: '/ai-writing'
      fullPath: '/admin/articles/ai-writing'
      preLoaderRoute: typeof AuthenticatedAdminArticlesAiWritingRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/ai-seo': {
      id: '/_authenticated/admin/articles/ai-seo'
      path: '/ai-seo'
      fullPath: '/admin/articles/ai-seo'
      preLoaderRoute: typeof AuthenticatedAdminArticlesAiSeoRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/$id': {
      id: '/_authenticated/admin/articles/$id'
      path: '/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIdRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/revisions/': {
      id: '/_authenticated/admin/articles/revisions/'
      path: '/'
      fullPath: '/admin/articles/revisions/'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRevisionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRevisionsRoute
    }
    '/_authenticated/admin/articles/preview/': {
      id: '/_authenticated/admin/articles/preview/'
      path: '/'
      fullPath: '/admin/articles/preview/'
      preLoaderRoute: typeof AuthenticatedAdminArticlesPreviewIndexRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesPreviewRoute
    }
    '/_authenticated/admin/categories/$id/settings': {
      id: '/_authenticated/admin/categories/$id/settings'
      path: '/settings'
      fullPath: '/admin/categories/$id/settings'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIdSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesIdRoute
    }
    '/_authenticated/admin/categories/$id/edit': {
      id: '/_authenticated/admin/categories/$id/edit'
      path: '/edit'
      fullPath: '/admin/categories/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesIdRoute
    }
    '/_authenticated/admin/categories/$id/articles': {
      id: '/_authenticated/admin/categories/$id/articles'
      path: '/articles'
      fullPath: '/admin/categories/$id/articles'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIdArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesIdRoute
    }
    '/_authenticated/admin/categories/$id/analytics': {
      id: '/_authenticated/admin/categories/$id/analytics'
      path: '/analytics'
      fullPath: '/admin/categories/$id/analytics'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesIdRoute
    }
    '/_authenticated/admin/articles/revisions/$articleId': {
      id: '/_authenticated/admin/articles/revisions/$articleId'
      path: '/$articleId'
      fullPath: '/admin/articles/revisions/$articleId'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRevisionsArticleIdRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRevisionsRoute
    }
    '/_authenticated/admin/articles/preview/$articleId': {
      id: '/_authenticated/admin/articles/preview/$articleId'
      path: '/$articleId'
      fullPath: '/admin/articles/preview/$articleId'
      preLoaderRoute: typeof AuthenticatedAdminArticlesPreviewArticleIdRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesPreviewRoute
    }
  }
}

interface AuthenticatedAdminArticlesPreviewRouteChildren {
  AuthenticatedAdminArticlesPreviewArticleIdRoute: typeof AuthenticatedAdminArticlesPreviewArticleIdRoute
  AuthenticatedAdminArticlesPreviewIndexRoute: typeof AuthenticatedAdminArticlesPreviewIndexRoute
}

const AuthenticatedAdminArticlesPreviewRouteChildren: AuthenticatedAdminArticlesPreviewRouteChildren =
  {
    AuthenticatedAdminArticlesPreviewArticleIdRoute:
      AuthenticatedAdminArticlesPreviewArticleIdRoute,
    AuthenticatedAdminArticlesPreviewIndexRoute:
      AuthenticatedAdminArticlesPreviewIndexRoute,
  }

const AuthenticatedAdminArticlesPreviewRouteWithChildren =
  AuthenticatedAdminArticlesPreviewRoute._addFileChildren(
    AuthenticatedAdminArticlesPreviewRouteChildren,
  )

interface AuthenticatedAdminArticlesRevisionsRouteChildren {
  AuthenticatedAdminArticlesRevisionsArticleIdRoute: typeof AuthenticatedAdminArticlesRevisionsArticleIdRoute
  AuthenticatedAdminArticlesRevisionsIndexRoute: typeof AuthenticatedAdminArticlesRevisionsIndexRoute
}

const AuthenticatedAdminArticlesRevisionsRouteChildren: AuthenticatedAdminArticlesRevisionsRouteChildren =
  {
    AuthenticatedAdminArticlesRevisionsArticleIdRoute:
      AuthenticatedAdminArticlesRevisionsArticleIdRoute,
    AuthenticatedAdminArticlesRevisionsIndexRoute:
      AuthenticatedAdminArticlesRevisionsIndexRoute,
  }

const AuthenticatedAdminArticlesRevisionsRouteWithChildren =
  AuthenticatedAdminArticlesRevisionsRoute._addFileChildren(
    AuthenticatedAdminArticlesRevisionsRouteChildren,
  )

interface AuthenticatedAdminArticlesRouteChildren {
  AuthenticatedAdminArticlesIdRoute: typeof AuthenticatedAdminArticlesIdRoute
  AuthenticatedAdminArticlesAiSeoRoute: typeof AuthenticatedAdminArticlesAiSeoRoute
  AuthenticatedAdminArticlesAiWritingRoute: typeof AuthenticatedAdminArticlesAiWritingRoute
  AuthenticatedAdminArticlesAllRoute: typeof AuthenticatedAdminArticlesAllRoute
  AuthenticatedAdminArticlesApprovedRoute: typeof AuthenticatedAdminArticlesApprovedRoute
  AuthenticatedAdminArticlesArchivedRoute: typeof AuthenticatedAdminArticlesArchivedRoute
  AuthenticatedAdminArticlesContentScoreRoute: typeof AuthenticatedAdminArticlesContentScoreRoute
  AuthenticatedAdminArticlesCreateRoute: typeof AuthenticatedAdminArticlesCreateRoute
  AuthenticatedAdminArticlesDraftsRoute: typeof AuthenticatedAdminArticlesDraftsRoute
  AuthenticatedAdminArticlesInternalLinkingRoute: typeof AuthenticatedAdminArticlesInternalLinkingRoute
  AuthenticatedAdminArticlesPreviewRoute: typeof AuthenticatedAdminArticlesPreviewRouteWithChildren
  AuthenticatedAdminArticlesPublishedRoute: typeof AuthenticatedAdminArticlesPublishedRoute
  AuthenticatedAdminArticlesRelatedRoute: typeof AuthenticatedAdminArticlesRelatedRoute
  AuthenticatedAdminArticlesReviewRoute: typeof AuthenticatedAdminArticlesReviewRoute
  AuthenticatedAdminArticlesRevisionsRoute: typeof AuthenticatedAdminArticlesRevisionsRouteWithChildren
  AuthenticatedAdminArticlesScheduledRoute: typeof AuthenticatedAdminArticlesScheduledRoute
  AuthenticatedAdminArticlesSettingsRoute: typeof AuthenticatedAdminArticlesSettingsRoute
  AuthenticatedAdminArticlesTrashRoute: typeof AuthenticatedAdminArticlesTrashRoute
  AuthenticatedAdminArticlesWorkflowRoute: typeof AuthenticatedAdminArticlesWorkflowRoute
  AuthenticatedAdminArticlesIndexRoute: typeof AuthenticatedAdminArticlesIndexRoute
}

const AuthenticatedAdminArticlesRouteChildren: AuthenticatedAdminArticlesRouteChildren =
  {
    AuthenticatedAdminArticlesIdRoute: AuthenticatedAdminArticlesIdRoute,
    AuthenticatedAdminArticlesAiSeoRoute: AuthenticatedAdminArticlesAiSeoRoute,
    AuthenticatedAdminArticlesAiWritingRoute:
      AuthenticatedAdminArticlesAiWritingRoute,
    AuthenticatedAdminArticlesAllRoute: AuthenticatedAdminArticlesAllRoute,
    AuthenticatedAdminArticlesApprovedRoute:
      AuthenticatedAdminArticlesApprovedRoute,
    AuthenticatedAdminArticlesArchivedRoute:
      AuthenticatedAdminArticlesArchivedRoute,
    AuthenticatedAdminArticlesContentScoreRoute:
      AuthenticatedAdminArticlesContentScoreRoute,
    AuthenticatedAdminArticlesCreateRoute:
      AuthenticatedAdminArticlesCreateRoute,
    AuthenticatedAdminArticlesDraftsRoute:
      AuthenticatedAdminArticlesDraftsRoute,
    AuthenticatedAdminArticlesInternalLinkingRoute:
      AuthenticatedAdminArticlesInternalLinkingRoute,
    AuthenticatedAdminArticlesPreviewRoute:
      AuthenticatedAdminArticlesPreviewRouteWithChildren,
    AuthenticatedAdminArticlesPublishedRoute:
      AuthenticatedAdminArticlesPublishedRoute,
    AuthenticatedAdminArticlesRelatedRoute:
      AuthenticatedAdminArticlesRelatedRoute,
    AuthenticatedAdminArticlesReviewRoute:
      AuthenticatedAdminArticlesReviewRoute,
    AuthenticatedAdminArticlesRevisionsRoute:
      AuthenticatedAdminArticlesRevisionsRouteWithChildren,
    AuthenticatedAdminArticlesScheduledRoute:
      AuthenticatedAdminArticlesScheduledRoute,
    AuthenticatedAdminArticlesSettingsRoute:
      AuthenticatedAdminArticlesSettingsRoute,
    AuthenticatedAdminArticlesTrashRoute: AuthenticatedAdminArticlesTrashRoute,
    AuthenticatedAdminArticlesWorkflowRoute:
      AuthenticatedAdminArticlesWorkflowRoute,
    AuthenticatedAdminArticlesIndexRoute: AuthenticatedAdminArticlesIndexRoute,
  }

const AuthenticatedAdminArticlesRouteWithChildren =
  AuthenticatedAdminArticlesRoute._addFileChildren(
    AuthenticatedAdminArticlesRouteChildren,
  )

interface AuthenticatedAdminCategoriesIdRouteChildren {
  AuthenticatedAdminCategoriesIdAnalyticsRoute: typeof AuthenticatedAdminCategoriesIdAnalyticsRoute
  AuthenticatedAdminCategoriesIdArticlesRoute: typeof AuthenticatedAdminCategoriesIdArticlesRoute
  AuthenticatedAdminCategoriesIdEditRoute: typeof AuthenticatedAdminCategoriesIdEditRoute
  AuthenticatedAdminCategoriesIdSettingsRoute: typeof AuthenticatedAdminCategoriesIdSettingsRoute
}

const AuthenticatedAdminCategoriesIdRouteChildren: AuthenticatedAdminCategoriesIdRouteChildren =
  {
    AuthenticatedAdminCategoriesIdAnalyticsRoute:
      AuthenticatedAdminCategoriesIdAnalyticsRoute,
    AuthenticatedAdminCategoriesIdArticlesRoute:
      AuthenticatedAdminCategoriesIdArticlesRoute,
    AuthenticatedAdminCategoriesIdEditRoute:
      AuthenticatedAdminCategoriesIdEditRoute,
    AuthenticatedAdminCategoriesIdSettingsRoute:
      AuthenticatedAdminCategoriesIdSettingsRoute,
  }

const AuthenticatedAdminCategoriesIdRouteWithChildren =
  AuthenticatedAdminCategoriesIdRoute._addFileChildren(
    AuthenticatedAdminCategoriesIdRouteChildren,
  )

interface AuthenticatedAdminCategoriesRouteChildren {
  AuthenticatedAdminCategoriesIdRoute: typeof AuthenticatedAdminCategoriesIdRouteWithChildren
  AuthenticatedAdminCategoriesActivityRoute: typeof AuthenticatedAdminCategoriesActivityRoute
  AuthenticatedAdminCategoriesAllRoute: typeof AuthenticatedAdminCategoriesAllRoute
  AuthenticatedAdminCategoriesCreateRoute: typeof AuthenticatedAdminCategoriesCreateRoute
  AuthenticatedAdminCategoriesImportExportRoute: typeof AuthenticatedAdminCategoriesImportExportRoute
  AuthenticatedAdminCategoriesSettingsRoute: typeof AuthenticatedAdminCategoriesSettingsRoute
  AuthenticatedAdminCategoriesIndexRoute: typeof AuthenticatedAdminCategoriesIndexRoute
}

const AuthenticatedAdminCategoriesRouteChildren: AuthenticatedAdminCategoriesRouteChildren =
  {
    AuthenticatedAdminCategoriesIdRoute:
      AuthenticatedAdminCategoriesIdRouteWithChildren,
    AuthenticatedAdminCategoriesActivityRoute:
      AuthenticatedAdminCategoriesActivityRoute,
    AuthenticatedAdminCategoriesAllRoute: AuthenticatedAdminCategoriesAllRoute,
    AuthenticatedAdminCategoriesCreateRoute:
      AuthenticatedAdminCategoriesCreateRoute,
    AuthenticatedAdminCategoriesImportExportRoute:
      AuthenticatedAdminCategoriesImportExportRoute,
    AuthenticatedAdminCategoriesSettingsRoute:
      AuthenticatedAdminCategoriesSettingsRoute,
    AuthenticatedAdminCategoriesIndexRoute:
      AuthenticatedAdminCategoriesIndexRoute,
  }

const AuthenticatedAdminCategoriesRouteWithChildren =
  AuthenticatedAdminCategoriesRoute._addFileChildren(
    AuthenticatedAdminCategoriesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminAmbassadorsRoute: typeof AuthenticatedAdminAmbassadorsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRouteWithChildren
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRouteWithChildren
  AuthenticatedAdminCommentsRoute: typeof AuthenticatedAdminCommentsRoute
  AuthenticatedAdminEmbassiesRoute: typeof AuthenticatedAdminEmbassiesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTickerRoute: typeof AuthenticatedAdminTickerRoute
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAdminWarMonitorRoute: typeof AuthenticatedAdminWarMonitorRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminAmbassadorsRoute: AuthenticatedAdminAmbassadorsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRouteWithChildren,
  AuthenticatedAdminCategoriesRoute:
    AuthenticatedAdminCategoriesRouteWithChildren,
  AuthenticatedAdminCommentsRoute: AuthenticatedAdminCommentsRoute,
  AuthenticatedAdminEmbassiesRoute: AuthenticatedAdminEmbassiesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTickerRoute: AuthenticatedAdminTickerRoute,
  AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
  AuthenticatedAdminWarMonitorRoute: AuthenticatedAdminWarMonitorRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  EpaperRoute: EpaperRoute,
  LatestRoute: LatestRoute,
  NewsletterRoute: NewsletterRoute,
  PodcastRoute: PodcastRoute,
  PopularRoute: PopularRoute,
  ProgramsRoute: ProgramsRoute,
  VideoRoute: VideoRoute,
  AmbassadorIdRoute: AmbassadorIdRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  EmbassyIdRoute: EmbassyIdRoute,
  SectionSlugRoute: SectionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
